### PR TITLE
Move .github/mistaken-pull-closer.yml to .github/workflows/

### PR DESCRIPTION
**Pull request by cclauss**
GitHub Actions must be in `.github/workflows`

### CODE REVIEW

**Comment by cclauss** [comment]
@gsathya Please make this change to upstream.

**Comment by Nytelife26** [comment]
@cclauss As evidenced by the fact that the Mistaken Pull Closer automatically denied your pull request, [it is meant to be there](https://github.com/probot/mistaken-pull-closer#configuration). Mistaken Pull Closer is *not* a workflow - rather, an integration.

**Comment by cclauss** [comment]
This PR ONLY worked because it put the file in the RIGHT place.

**Comment by Nytelife26** [comment]
> This PR ONLY worked because it put the file in the RIGHT place.

That's not how that works. It runs workflows from the repository, not
from the pull request. Not to mention that if you look at other PRs the
same thing happened.

Once again, go take a look at the configuration. I was just trying to be
helpful and point it out.

**Pull request closed without merging**
