### PR TITLE
Travis CI: Use flake8 to find Python syntax errors

### PR DESCRIPTION
**Pull request by cclauss**
Bug report: https://bugs.chromium.org/p/v8/issues/detail?id=8594

Just 1.4% of the v8 codebase is Python but that code contains:
* Python 2:  ~___4 syntax errors___ and 26 undefined names.~
* Python 3: ~___76 syntax errors___ and 42 undefined names.~

__UPDATE:__
* Python 2:  ___0 syntax errors___ and 0 undefined names.
* Python 3: ___1 syntax errors___ and 1 undefined names.

Output: https://travis-ci.com/cclauss/v8

__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. Most other flake8 issues are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

### CODE REVIEW

**Comment by ibrahimgorashi98** [comment]
Thanks pro i'm so happy

**Comment by bmsdave** [comment]
we moved the changes to https://chromium-review.googlesource.com/c/v8/v8/+/1454477/9
This pull request can be closed
@cclauss

**Comment by cclauss** [comment]
I will close when that bugfix lands.

**Comment by bmsdave** [comment]
Done.

See:
https://chromium-review.googlesource.com/c/v8/v8/+/1470121
https://chromium-review.googlesource.com/c/v8/v8/+/1470101
https://chromium-review.googlesource.com/c/v8/v8/+/1470122
https://chromium-review.googlesource.com/c/v8/v8/+/1470123

**Comment by cclauss** [comment]
Very impressive work!!  Congratulations and thank you.

**Comment by cclauss** [comment]
Travis was turned off for this repo but here are the current results.  We are getting __tantalizingly close...__

The issues are that __execfile()__ and __file()__ were removed in Python 3 and __FileNotFoundError__ does not exist in Python 2.

Current v8/v8 issues on Python 3: flake8 testing of https://github.com/v8/v8 on Python 3.7.1

$ __flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics__
```
./third_party/binutils/download.py:30:8: F821 undefined name 'file'
  with file(filename, 'r') as f:
       ^
./third_party/binutils/download.py:36:8: F821 undefined name 'file'
  with file(filename, 'w') as f:
       ^
./test/preparser/testcfg.py:69:5: F821 undefined name 'execfile'
    execfile(pathname, {"Test": Test, "Template": Template})
    ^
./tools/testrunner/outproc/mkgrokdump.py:23:8: F632 use ==/!= to compare str, bytes, and int literals
    if diffstring is not "":
       ^
1     F632 use ==/!= to compare str, bytes, and int literals
3     F821 undefined name 'execfile'
4
```

Current v8/v8 issues on Python 2: flake8 testing of https://github.com/v8/v8 on Python 2.7.15

$ __flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics__
```
./tools/locs.py:324:10: F821 undefined name 'FileNotFoundError'
  except FileNotFoundError:
         ^
./tools/testrunner/outproc/mkgrokdump.py:23:8: F632 use ==/!= to compare str, bytes, and int literals
    if diffstring is not "":
       ^
1     F632 use ==/!= to compare str, bytes, and int literals
1     F821 undefined name 'FileNotFoundError'
2
```

**Comment by bmsdave** [comment]
@cclauss sorry for delay. I will do these tasks this week.

**Comment by cclauss** [comment]
@bmsdave @refack Can we close this issue or not yet?

**Comment by hayd** [comment]
Six months to go!

Is CI being run on python 3? Is there a good way to split up the future porting work (post syntax)? Presumably lots fail even with this patch?

**Comment by cclauss** [comment]
[flake8](http://flake8.pycqa.org) testing of https://github.com/v8/v8 on Python 3.7.1

$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./test/preparser/testcfg.py:69:5: F821 undefined name 'execfile'
    execfile(pathname, {"Test": Test, "Template": Template})
    ^
./tools/wasm-compilation-hints/wasm-objdump-compilation-hints.py:37:54: E999 SyntaxError: invalid syntax
          print "Custom section compilationHints with", num_hints, "hints:"
                                                     ^
1     E999 SyntaxError: invalid syntax
1     F821 undefined name 'execfile'
2
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. These 5 are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by hayd** [comment]
SyntaxError is just the start of the porting story, is there buy-in to run python 3 on CI? (Or is this already happening?)

**Comment by cclauss** [comment]
There is a lot of traffic on the upstream repo about Python 3 experimentation but I do find it frustrating that basic linting is not yet done to avoid backsliding like we see in these two issues.

**Comment by cclauss** [comment]
Added #33 and #34 here if someone would be willing to push those changes upstream.

**Comment by cclauss** [comment]
We are backsliding:

91 days until Python 2 end of life. https://www.python.org/doc/sunset-python-2

[flake8](http://flake8.pycqa.org) testing of https://github.com/v8/v8 on Python 3.7.1

$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./test/preparser/testcfg.py:69:5: F821 undefined name 'execfile'
    execfile(pathname, {"Test": Test, "Template": Template})
    ^
./tools/regexp-sequences.py:27:12: F821 undefined name 'xrange'
  for i in xrange(seqlen):
           ^
./tools/regexp-sequences.py:35:18: F821 undefined name 'xrange'
        for i in xrange(seqlen):
                 ^
./tools/regexp-sequences.py:42:18: F821 undefined name 'xrange'
        for i in xrange(seqlen):
                 ^
./tools/regexp-sequences.py:60:12: F821 undefined name 'xrange'
  for i in xrange(max_seq):
           ^
./tools/wasm-compilation-hints/wasm-objdump-compilation-hints.py:37:54: E999 SyntaxError: invalid syntax
          print "Custom section compilationHints with", num_hints, "hints:"
                                                     ^
1     E999 SyntaxError: invalid syntax
5     F821 undefined name 'execfile'
6
```

**Pull request closed without merging**
